loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: eu-west-2           # Replace with your actual region if different
      bucketnames: mintairlogs-chunks  # Bucket for chunk storage
      s3forcepathstyle: false
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h        # 28 days retention
  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
      chunks: mintairlogs-chunks
      ruler: mintairlogs-ruler
      admin: mintairlogs
    s3:
      # You can either use the s3 URL syntax or fill in the individual fields.
      # Using s3 URL:
      s3: s3://<your-access-key>:<your-secret-key>@s3.eu-west-2.amazonaws.com/mintairlogs-chunks
      # Alternatively, you can specify the individual fields:
      endpoint: s3.eu-west-2.amazonaws.com
      region: eu-west-2
      secretAccessKey: <your-secret-key>
      accessKeyId: <your-access-key>
      signatureVersion: v4
      s3ForcePathStyle: false
      insecure: false
      http_config: {}

deploymentMode: SimpleScalable

backend:
  replicas: 3
read:
  replicas: 3
write:
  replicas: 3

# Disable minio storage
minio:
  enabled: false
